name: "Test Environment"
    description: "Runs tests for a specified environment"
    inputs:
      environment:
        description: "The target environment (dev, staging, preprod, prod)"
        required: true
      repository:
        description: "The repository to checkout"
        required: true
      path:
        description: "The path to the repository"
        required: true
    runs:
      using: "composite"
      steps:
        - run: echo "Testing ${{ inputs.environment }}..."
          shell: cmd
        - uses: actions/checkout@v4
          with:
            repository: ${{ inputs.repository }}
            path: ${{ inputs.path }}
        - run: npm install
          shell: cmd
          working-directory: ${{ inputs.path }}
        - run: npm run greetings greetings_${{ inputs.environment }}
          shell: cmd
          working-directory: ${{ inputs.path }}