name: Python Greetings Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
      steps:
        - name: Checkout code (pipeline definition)
          uses: actions/checkout@v4
          with:
            repository: xdaavis/ld-pieg-konv
              - name: Checkout python-greetings
                uses: actions/checkout@v4
                with:
                  repository: mtararujs/python-greetings
                  path: python-greetings
                    - name: Informācija
                    run: echo "Instalēju atkarības..."
                    - name: Install dependencies
                    run: pip install -r requirements.txt
                    working-directory: python-greetings

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Deploy to dev
        uses: ./.github/actions/deploy-action
        with:
          environment: dev
          port: 7001
          repository: xdaavis/ld-pieg-konv
          path: python-greetings

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Test dev
        uses: ./.github/actions/test-action
        with:
          environment: dev
          repository: xdaavis/ld-pieg-konv
          path: course-js-api-framework

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Deploy to staging
        uses: ./.github/actions/deploy-action
        with:
          environment: staging
          port: 7002
          repository: xdaavis/ld-pieg-konv
          path: python-greetings

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - name: Test staging
        uses: ./.github/actions/test-action
        with:
          environment: staging
          repository: xdaavis/ld-pieg-konv
          path: course-js-api-framework

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - name: Deploy to preprod
        uses: ./.github/actions/deploy-action
        with:
          environment: preprod
          port: 7003
          repository: xdaavis/ld-pieg-konv
          path: python-greetings

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - name: Test preprod
        uses: ./.github/actions/test-action
        with:
          environment: preprod
          repository: xdaavis/ld-pieg-konv
          path: course-js-api-framework

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Deploy to prod
        uses: ./.github/actions/deploy-action
        with:
          environment: prod
          port: 7004
          repository: xdaavis/ld-pieg-konv
          path: python-greetings

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - name: Test prod
        uses: ./.github/actions/test-action
        with:
          environment: prod
          repository: xdaavis/ld-pieg-konv
          path: course-js-api-framework